In [1]:
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt
from pylab import rcParams
import urllib
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [18]:
np.set_printoptions(precision=4, suppress =True)
%matplotlib inline
rcParams['figure.figsize']=7,4
plt.style.use('seaborn-whitegrid')

In [19]:
input_data = pd.read_csv('Dataset_7.1.csv', header=0, delimiter=';')
# data = input_data.drop(['ppnnr'], axis='columns')
data = input_data
data['Group'].replace({2: 1}, inplace=True)
data['Group'].replace({3: 2}, inplace=True)
data = data.dropna()
data = data.drop(['ppnnr'],axis='columns')
data.head()

,Group,geslacht,leeftijd,BMI,SBP,DBP,Hypertensie,DM,Hyperchol,Statine,...,MDRD,LDL,HDL,Trigly,Symp_Inf_aanw,Old_Inf_aanw,WMH_PVD_ext,PVS_BG_ext,PVS_CS_ext,MB_totaal_aanw
0,1,1,78,27.968016,147.5,83.5,0,0,1,1,...,0,1.9,1.2,1.95,1.0,1.0,1.0,1.0,1.0,0.0
1,1,2,65,22.656250,133.5,84.0,1,0,1,1,...,0,3.5,2.0,1.31,0.0,0.0,1.0,0.0,1.0,0.0
2,1,2,55,31.202564,182.0,113.0,1,0,1,1,...,0,1.9,1.8,2.03,1.0,0.0,0.0,0.0,1.0,0.0
3,1,1,46,32.824138,152.5,93.5,1,0,1,1,...,0,2.2,0.9,3.58,1.0,0.0,0.0,0.0,1.0,0.0
4,1,1,63,25.689562,140.0,82.5,0,0,1,1,...,0,1.9,1.7,0.93,0.0,1.0,0.0,0.0,1.0,0.0

In [20]:
X_prime = data.drop(['Group'],axis='columns')

y = data['Group']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X_prime, y ,test_size=0.33, random_state = 17)

In [22]:
clf = neighbors.KNeighborsClassifier()
clf.fit(X_train, y_train)
print(clf)

KNeighborsClassifier()

In [23]:
y_pred = clf.predict(X_test)

print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.58      0.86      0.69        22
           2       0.50      0.18      0.26        17

    accuracy                           0.56        39
   macro avg       0.54      0.52      0.48        39
weighted avg       0.54      0.56      0.50        39